"""empty message

Revision ID: 6f13363ee200
Revises: 49a5b5ec0a2f
Create Date: 2023-02-15 16:47:42.087029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f13363ee200'
down_revision = '49a5b5ec0a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mypoke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('catch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catch',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name='catch_pokemon_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='catch_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='catch_pkey')
    )
    op.drop_table('mypoke')
    # ### end Alembic commands ###
